# Generated by Django 5.2.12 on 2026-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('veiculo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=300)),
                ('acessoria', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('apreendido', 'Apreendido'), ('liberado', 'Liberado'), ('em_processo', 'Em Processo')], default='apreendido', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data'],
            },
        ),
    ]
