# Generated by Django 5.2.12 on 2026-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="imagem_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
