# Generated by Django 5.2.12 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0003_add_imagem_url_2_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="ano_reg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="cidade",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="custo_operacao",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="data_apreensao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="marca",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="observacoes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="quem_executou",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="semana_iso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="valor_recebido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="valor_servico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="local",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="veiculo",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
