# Generated by Django 5.2.12 on 2026-03-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0004_add_new_custody_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeiculoHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE_CREATED", "Veículo criado"),
                            ("STATUS_CHANGED", "Status alterado"),
                            ("COST_CHANGED", "Custo alterado"),
                            ("DATA_CHANGED", "Dados alterados"),
                            ("PHOTO_ADDED", "Foto adicionada"),
                            ("PHOTO_REMOVED", "Foto removida"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("old_value", models.CharField(blank=True, default="", max_length=500)),
                ("new_value", models.CharField(blank=True, default="", max_length=500)),
                ("user", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico do Veículo",
                "verbose_name_plural": "Históricos dos Veículos",
                "ordering": ["-created_at"],
            },
        ),
    ]
